name: ihl
description: IHL Health User App.
publish_to: "none"
version: 10.0.64+117 #Increment A.B.C for versionName and '+D' for versionCode.
#last version  10.0.53+106 - date-> 19 May 2023
environment:
  sdk: ">=2.10.0 <=3.3.3"

dependencies:
  aad_oauth: ^0.4.4
  add_2_calendar: ^2.2.4
  animated_text_kit: ^4.2.1
  audioplayers: ^3.0.1
  auto_size_text: ^3.0.0
  awesome_dialog: ^3.0.2
  badges: ^2.0.1
  basic_utils: ^5.5.4
  bubble_bottom_bar: ^2.0.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.0
  charts_flutter: null
  chips_choice: ^2.0.1
  connectanum: ^2.0.2
  connectivity_plus: ^3.0.3
  connectivity_wrapper: ^1.0.6
  count_stepper: ^0.0.4
  crisp: ^0.3.1
  crypto: any
  cupertino_icons: ^1.0.3
  customgauge: ^1.0.1
  data_connection_checker: ^0.3.4
  date_range_picker: ^1.0.6
  date_time_format: ^2.0.1
  device_info_plus: ^8.1.0
  device_preview: null
  dio: ^4.0.6
  disposebag: ^1.5.0
  dots_indicator: null
  dotted_border: ^2.0.0+1
  encrypt: ^5.0.1
  equatable: ^2.0.5
  expandable: ^5.0.1
  expansion_card: ^0.1.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.4
  external_app_launcher: ^3.1.0
  #  facebook_app_events: ^0.18.3
  ffi: null
  file_picker: ^5.2.6
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_dynamic_links: ^5.0.17
  firebase_messaging: ^14.3.0
  firebase_messaging_platform_interface: ^4.1.6
  fl_chart: ^0.36.4
  flashy_tab_bar2: ^0.0.4
  floating_action_bubble: null
  fluentui_icons: ^1.0.0
  flushbar: ^1.10.4
  flutter:
    sdk: flutter
  flutter_alarm_clock: ^0.0.2
  flutter_circular_text: ^0.3.1
  flutter_datetime_picker: ^1.5.1
  flutter_document_picker: ^5.1.0
  flutter_downloader: ^1.7.0
  flutter_exif_rotation: ^0.5.1
  flutter_highlight: ^0.7.0
  flutter_icons: ^1.1.0
  flutter_inappwebview: ^5.8.0
  flutter_linkify: ^5.0.2
  flutter_lints: ^2.0.2
  flutter_local_notifications: ^9.5.3+1
  flutter_markdown: ^0.6.6
  flutter_native_timezone: ^2.0.0
  flutter_neumorphic: ^3.2.0
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.0
  flutter_speed_dial: null
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_styled_toast: ^2.0.0
  flutter_svg: ^2.0.4
  flutter_typeahead: ^4.3.7
  flutter_zoom_drawer: ^2.1.1
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^10.4.0
  gap: ^2.0.0
  geolocator: ^9.0.2
  get: ^4.3.8
  get_storage: ^2.0.0
  getwidget: ^3.0.1
  giff_dialog: ^1.0.1
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.8
  google_sign_in: ^6.0.2
  googleapis: ^10.1.0
  health: ^4.4.0
  hive: ^2.0.4
  hive_flutter: null
  html: ^0.15.0
  http: ^0.13.3
  image_cropper: ^3.0.1
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.4+1
  image_watermark: ^0.0.4
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  jiffy: ^5.0.0
  jitsi_meet: ^4.0.0
  loading_skeleton: ^1.0.2
  location: ^4.3.0
  lottie: ^2.3.1
  marquee_widget: ^1.2.0
  meta: ^1.3.0
  native_device_orientation: ^1.0.0
  open_file_plus: ^3.4.0
  package_info_plus: ^1.4.0
  path_drawing: ^1.0.1
  path_provider: ^2.0.4
  pdf: ^3.6.0
  pedometer:
    git:
      url: https://github.com/feelfreelinux/flutter-plugins
      path: packages/pedometer
  percent_indicator: ^4.2.3
  permission_handler: ^10.1.0
  photo_view: ^0.14.0
  pie_chart: ^5.3.2
  pin_code_fields: ^7.3.0
  printing: ^5.6.0
  qr_code_scanner: ^1.0.1
  rating_bar: ^0.2.0
  razorpay_flutter: ^1.3.4
  responsive_sizer: ^3.1.0
  rflutter_alert: ^2.0.4
  rotated_corner_decoration: ^2.0.0
  scrollable_positioned_list: ^0.3.5
  sentry_flutter: ^7.5.0
  share_plus: ^6.3.1
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  showcaseview: ^2.0.2
  sizer: ^2.0.15
  sleek_circular_slider: ^2.0.1
  sliding_sheet: ^0.5.2
  sliver_calendar: ^1.0.0
  smooth_star_rating: ^1.1.1
  streaming_shared_preferences: ^2.0.0
  strings: ^0.2.2
  syncfusion_flutter_charts: ^21.1.37
  syncfusion_flutter_gauges: ^21.1.37
  syncfusion_flutter_pdfviewer: ^21.1.37
  syncfusion_flutter_sliders: ^21.1.37
  synchronized: ^3.0.0
  table_calendar: ^3.0.2
  timeline_list: ^0.0.6
  timeline_tile: ^2.0.0
  timelines: ^0.1.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.10
  # vibration: ^1.7.7
  video_player: ^2.7.0
  web_socket_channel: ^2.2.0
  webview_flutter: ^4.0.7
  cloud_firestore: ^4.0.1
  flutter_bloc: ^8.1.3
  image: ^3.0.1
  collection: ^1.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - newAssets/
    - newAssets/fonts/
    - newAssets/Icons/
    - newAssets/images/
    - newAssets/medicalFiles/
    - newAssets/Icons/vitalsDetails/
    - newAssets/Icons/statusIcons/
    - newAssets/Icons/speciality/
    - assets/audio/
    - assets/svgs/
    - assets/images/
    - assets/images/quantitys/
    - assets/lottieFiles/
    - assets/icons/
    - assets/images/diet/
    - assets/images/cardio/
    - assets/survey.json
    - assets/dietTips.json
    - assets/files.json
    - assets/dietFitnessRecommendations.json
    - assets/TeleConsultation.json
    - assets/reconnecting.json
    - assets/error.json
    - assets/profile_icons/
    - assets/gif/
  #Avenir.ttc
  fonts:
    #    - family: Avenir
    #      fonts:
    #        - asset: assets/fonts/Avenir.ttc
    #        - asset: assets/fonts/Avenir_Next.ttc
    #        - asset: assets/fonts/Avenir_Next_Condensed.ttc
    #          style: normal
    #          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    #    - asset: assets/fonts/Poppins-Black.ttf
    #          style: normal
    #          weight: 700
    - family: Customicons
      fonts:
        - asset: assets/fonts/Customicons.ttf
    - family: Arial
      fonts:
        - asset: assets/fonts/arial.ttf
