export './teleconsultationDashboard.dart';
export './consultationType.dart';
export './specialityType.dart';
export './selectConsultant.dart';
export './confirm_visit.dart';
export './FollowUpScreen.dart';
export './files/medicalFiles.dart';
export './myAppointments.dart';
export './selectClasses.dart';
