// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfJmWPl8uanp6db5nDbDPXxJTydbyfAWk',
    appId: '1:1068591848947:web:6cc5d826afd052b6048686',
    messagingSenderId: '1068591848947',
    projectId: 'indiahealthlinkapp',
    authDomain: 'indiahealthlinkapp.firebaseapp.com',
    databaseURL: 'https://indiahealthlinkapp.firebaseio.com',
    storageBucket: 'indiahealthlinkapp.appspot.com',
    measurementId: 'G-1G1SD9DWK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDywpqHSTvZnQj6LoqLv_cKCR3-UAXQaUw',
    appId: '1:1068591848947:android:4f1137c7fa84169d048686',
    messagingSenderId: '1068591848947',
    projectId: 'indiahealthlinkapp',
    databaseURL: 'https://indiahealthlinkapp.firebaseio.com',
    storageBucket: 'indiahealthlinkapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2xd6q_YXHnAG9nU5b5jrTbA8PsxrI5Dg',
    appId: '1:1068591848947:ios:a0892cde6004b0ef048686',
    messagingSenderId: '1068591848947',
    projectId: 'indiahealthlinkapp',
    databaseURL: 'https://indiahealthlinkapp.firebaseio.com',
    storageBucket: 'indiahealthlinkapp.appspot.com',
    androidClientId: '1068591848947-af40qhdt61m9dgg3ak8pok5s7dmprm56.apps.googleusercontent.com',
    iosClientId: '1068591848947-dt9obhjlpto5sgm509jn0sc6k9v55sjq.apps.googleusercontent.com',
    iosBundleId: 'com.indiahealthlink.ihlhealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2xd6q_YXHnAG9nU5b5jrTbA8PsxrI5Dg',
    appId: '1:1068591848947:ios:ae574037af76630c048686',
    messagingSenderId: '1068591848947',
    projectId: 'indiahealthlinkapp',
    databaseURL: 'https://indiahealthlinkapp.firebaseio.com',
    storageBucket: 'indiahealthlinkapp.appspot.com',
    androidClientId: '1068591848947-af40qhdt61m9dgg3ak8pok5s7dmprm56.apps.googleusercontent.com',
    iosClientId: '1068591848947-83qsu0smjgrl0o56br22ouhgskdi31v4.apps.googleusercontent.com',
    iosBundleId: 'com.indiahealthlink.ihlCare',
  );
}
